name: training-size-matters

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10.12
  - u8darts-all=0.25.0
  - pytorch=2.0.1
  - prophet=1.1.4
  - matplotlib=3.7.2
  - pandas=2.0.3
  - numpy=1.24.4
  - requests=2.25.1
  - maya=0.6.1
  - icecream=2.1.3
  - optuna=3.5.0
  - scikit-learn=1.3.0
